name: Tests Menu Frutas

on:
  pull_request:
    branches: ["main"]
    paths:
      - "menu-interactivo-frutas/**"

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Run unit tests
        working-directory: menu-interactivo-frutas
        run: python -m unittest tests.test_menu_frutas -v

      - name: Run integration tests
        working-directory: menu-interactivo-frutas
        run: python -m unittest tests.test_integracion_menu -v
